syntax on
set autoindent
set backspace=indent,eol,start
set comments=s1:/*,mb:*,ex:*/,://,:%,:XCOMM,n:>,fb:-,fb:*,fb:#
set expandtab
set fenc=
set fileencodings=utf8,latin2
set formatoptions=tcq1j
set incsearch
set indentexpr=
set modeline
set mouse=ni
set nobackup
set nocindent
set nohlsearch
set nowritebackup
set ruler
set shiftround
set shiftwidth=4
set showcmd
set showmode
set softtabstop=4
set tabstop=4
set laststatus=2
set statusline=%n\ %y\ %<%f\ %h%m%r%=%-14.(%l,%c%V%)\ %P
set noequalalways
nohlsearch

augroup lang_local
    autocmd!
    autocmd BufEnter            *.html  setlocal indentexpr=
    autocmd BufNewFile,BufRead  *.py    setlocal ai
    autocmd BufNewFile,BufRead  *.py    setlocal ts=4
    autocmd BufNewFile,BufRead  *.py    setlocal sts=4
    autocmd BufNewFile,BufRead  *.py    setlocal et
    autocmd BufNewFile,BufRead  *.py    setlocal sw=4
    autocmd BufNewFile,BufRead  *.py    setlocal smartindent cinwords=if,elif,else,for,while,try,except,finally,def,class
    autocmd BufWritePre         *.py    1,$s/\s\+$//e

    autocmd FileType python             setlocal omnifunc=pythoncomplete#Complete
    autocmd FileType javascript         setlocal omnifunc=javascriptcomplete#CompleteJS
    autocmd FileType html               setlocal omnifunc=htmlcomplete#CompleteTags
    autocmd FileType css                setlocal omnifunc=csscomplete#CompleteCSS

    autocmd FileType make               setlocal noexpandtab
augroup END

inoremap <expr> <C-Space> pumvisible() \|\| &omnifunc == '' ?
\ "\<lt>C-n>" :
\ "\<lt>C-x>\<lt>C-o><c-r>=pumvisible() ?" .
\ "\"\\<lt>c-n>\\<lt>c-p>\\<lt>c-n>\" :" .
\ "\" \\<lt>bs>\\<lt>C-n>\"\<CR>"
imap <C-@> <C-Space>

set completeopt=longest,menuone
"inoremap <Nul> <C-x><C-o>
"autocmd FileType python python
highlight PmenuSel ctermbg=green gui=bold


" highlight trailing whitespace
highlight ExtraWhitespace ctermbg=red guibg=red

augroup colors_local
    autocmd!
    autocmd ColorScheme         *   highlight ExtraWhitespace guibg=red
    autocmd BufEnter            *   match ExtraWhitespace /\s\+$/
    autocmd InsertEnter         *   match ExtraWhitespace /\s\+\%#\@<!$/
    autocmd InsertLeave         *   match ExtraWhiteSpace /\s\+$/
augroup END

highlight CursorLine   cterm=NONE ctermbg=darkgrey guibg=lightgrey
highlight CursorColumn cterm=NONE ctermbg=darkgrey guibg=lightgrey
highlight ColorColumn  cterm=NONE ctermbg=darkgrey guibg=lightgrey

augroup cursor_colors
    autocmd!
    autocmd FileType *           setlocal cursorline
    autocmd FileType *           setlocal colorcolumn=79,80
    autocmd FileType help        setlocal nocursorline
    autocmd FileType help        setlocal colorcolumn=
augroup END

syn spell toplevel
set spelllang=pl,en
"" Enable spell checking for any unknown filetype
set spell
augroup spell_local
    autocmd!
    "" Disable spell checking for any known filetype...
    autocmd FileType *           setlocal nospell
    "" ...unless it is one of the following:
    autocmd FileType gitcommit   setlocal spell
    autocmd FileType mail        setlocal spell
    autocmd FileType rst         setlocal spell
    autocmd FileType txt         setlocal spell
augroup END

set nojoinspaces    " Do not insert double spaces.  After a peroid.
set textwidth=78
augroup textwidth_local
    autocmd!
    autocmd FileType conf        setlocal textwidth=0
    autocmd FileType muttrc      setlocal textwidth=0
    autocmd FileType python      setlocal textwidth=0
    autocmd FileType ruby        setlocal textwidth=0
    autocmd FileType sh          setlocal textwidth=0
    autocmd FileType sql         setlocal textwidth=0
    autocmd FileType vim         setlocal textwidth=0
    autocmd FileType xml         setlocal textwidth=0
augroup END

augroup rails
    autocmd FileType ruby       setlocal tabstop=2
    autocmd FileType ruby       setlocal shiftwidth=2
    autocmd FileType ruby       setlocal softtabstop=2
augroup END

" http://learnvimscriptthehardway.stevelosh.com/

"echo '>^.^<'
nnoremap - ddp
nnoremap _ ddkP
inoremap <c-u> <esc>viwUea
nnoremap <c-u> viwUe

source ~/.vim/ez_scroll_mid.vim

source ~/.vim/personal.vim
