---
- name: install shell packages
  apt:
    name:
      - bash
      - bash-completion
      - screen
    state: present
- name: install utility packages
  apt:
    name:
      - ansible
      - apg
      - bar
      - ca-certificates
      - curl
      - dos2unix
      - gnupg2
      - grc
      - htop
      - hwinfo
      - iotop
      - less
      - lsof
      - mc
      - mlocate
      - mtr
      - ncdu
      - openssh-client
      - p7zip
      - p7zip-full
      - pigz
      - psmisc
      - rfkill
      - rlwrap
      - rsync
      - time
      - whois
      - zip
    state: present
- name: install debian-dev packages
  apt:
    name:
      - debhelper
      - devscripts
      - dh-make
    state: present
- name: install dictionary packages
  apt:
    name:
      - aspell-en
      - aspell-pl
      - hunspell-en-us
      - myspell-pl
    state: present
- name: install font packages
  apt:
    name:
      - fonts-liberation2
      - ttf-mscorefonts-installer
    state: present
- name: install main packages
  apt:
    name:
      - etckeeper
      - git
      - git-svn
      - subversion
      - sudo
      - vim
    state: present
- name: install latex packages
  apt:
    name:
      - texlive
      - texlive-bibtex-extra
      - texlive-fonts-extra
      - texlive-lang-polish
      - texlive-latex-extra
    state: present
- name: install programming packages
  apt:
    name:
      - build-essential
      - libsqlite3-dev
      - maven
      - nodejs
      - openjdk-11-jdk
      - poedit
      - python3
      - python3-dev
      - virtualenv
    state: present
