---
- name: copy docker apt key
  copy:
    src: docker.gpg
    dest: /tmp/docker.gpg
- name: add docker apt key
  apt_key:
    file: /tmp/docker.gpg
    state: present
- name: add docker repo
  template:
    src: docker.list.j2
    dest: /etc/apt/sources.list.d/docker.list
  register: docker_apt_list
- name: update apt repositories
  apt:
    update_cache: yes
  when: docker_apt_list.changed
- name: install docker
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: present
- name: configure docker daemon
  template:
    src: daemon.json.j2
    dest: /etc/docker/daemon.json

- name: enable dockerd service
  sysvinit:
    name: docker
    enabled: yes

- name: get the username running the deploy
  become: false
  local_action: command whoami
  register: username
- name: add user to docker group
  user:
    name: "{{ username.stdout }}"
    groups: docker
    append: yes


